version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: monthly
          timezone: Asia/Tokyo
      open-pull-requests-limit: 1
      groups:
          npm-dependencies:
              update-types: [minor, patch]
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
